name: CI-Docker

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
  
    - name: Send Compile action
      run: |
        export DISPATCH_ACTION="$(echo run_build)"
        echo "::set-env name=NEW_DISPATCH_ACTION::$DISPATCH_ACTION"
        
    - name: Repository test Dispatch to wlaunchELF
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: ${{ github.repository_owner }}/wlaunchELF
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '{"ref": "${{ github.ref }}"}'
